const {chromium}=require('playwright');const {spawn}=require('child_process');const fs=require('fs');const assert=require('assert');
(async()=>{const dir=fs.mkdtempSync(require('path').join(require('os').tmpdir(),'app-am-test-'));const server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3187',DATA_DIR:dir,ADMIN_SETUP_PASSWORD:'test-setup'},stdio:'ignore'});let browser;
try{for(let i=0;i<40;i++){try{await fetch('http://localhost:3187/api/auth/status');break}catch{await new Promise(r=>setTimeout(r,100))}}
const status=await (await fetch('http://localhost:3187/api/auth/status')).json();const setup=await fetch('http://localhost:3187/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:status.users.find(u=>u.role==='admin').id,password:'test-password',setupPassword:'test-setup'})});const cookie=setup.headers.get('set-cookie').split(';')[0];
browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();await context.addCookies([{name:'app_am_session',value:cookie.split('=')[1],url:'http://localhost:3187'}]);const page=await context.newPage();await page.goto('http://localhost:3187');await page.waitForFunction(()=>typeof renderManagement==='function');
await page.evaluate(()=>{renderManagement();openClientModal();const directory={requestPermission:async()=> 'granted',queryPermission:async()=> 'granted',getDirectoryHandle:async()=>directory,async *values(){}};getSavedHandle=async()=>directory;loadManagementClients=async()=>{};});
await page.locator('#clientName').fill('Prueba socios');await page.locator('#clientCif').fill('B12345678');await page.locator('#addClientPartner').click();await page.locator('[data-person-field=name]').fill('Socio de prueba');await page.locator('[data-person-field=dni]').fill('12345678A');await page.locator('[data-person-field=participation]').fill('60');await page.locator('#clientAdministrationType').selectOption({label:'Administradores solidarios'});
await page.locator('#peopleContactosTab').click();await page.locator('#addClientContact').click();await page.locator('#addClientContact').click();await page.locator('[data-person-kind=contact] [data-person-field=name]').nth(0).fill('Contacto uno');await page.locator('[data-person-kind=contact] [data-person-field=name]').nth(1).fill('Contacto dos');await page.locator('[name=clientPrimaryContact]').nth(0).check();await page.locator('[name=clientPrimaryContact]').nth(1).check();assert.equal(await page.locator('[name=clientPrimaryContact]:checked').count(),1);
await page.evaluate(()=>createClient({preventDefault(){},target:document.querySelector('#newClientForm')}));assert.match(await page.locator('#formMessage').textContent(),/correctamente/);
await page.evaluate(()=>openEditClient('Prueba socios'));assert.equal(await page.locator('[data-person-field=participation]').inputValue(),'60');await page.locator('[data-person-field=participation]').fill('75');await page.locator('#peopleContactosTab').click();await page.locator('[data-person-kind=contact] button').first().click();await page.evaluate(()=>createClient({preventDefault(){},target:document.querySelector('#newClientForm')}));
const saved=JSON.parse(fs.readFileSync(dir+'/app-metadata.json')).clients[0];assert.equal(saved.partners[0].participation,75);assert.equal(saved.contacts.length,1);assert.equal(saved.contacts[0].primary,true);
await page.reload();await page.evaluate(async()=>{renderManagement();await openEditClient('Prueba socios')});assert.equal(await page.locator('[data-person-field=participation]').inputValue(),'75');
await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.client-person-row').first().evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),1);
console.log('PASS: create, edit, server disk persistence, reload, exclusive primary, delete contact, mobile single column');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
